-- AlterTable
ALTER TABLE "students" ADD COLUMN     "address" VARCHAR(250),
ADD COLUMN     "caste" VARCHAR(80),
ADD COLUMN     "category" VARCHAR(50),
ADD COLUMN     "city" VARCHAR(80),
ADD COLUMN     "father_annual_income" DECIMAL(12,2),
ADD COLUMN     "father_mobile" VARCHAR(30),
ADD COLUMN     "father_name" VARCHAR(120),
ADD COLUMN     "father_occupation" VARCHAR(120),
ADD COLUMN     "father_qualification" VARCHAR(120),
ADD COLUMN     "guardian_name" VARCHAR(120),
ADD COLUMN     "guardian_phone" VARCHAR(30),
ADD COLUMN     "guardian_relationship" VARCHAR(80),
ADD COLUMN     "identification_mark" VARCHAR(200),
ADD COLUMN     "mother_annual_income" DECIMAL(12,2),
ADD COLUMN     "mother_mobile" VARCHAR(30),
ADD COLUMN     "mother_name" VARCHAR(120),
ADD COLUMN     "mother_occupation" VARCHAR(120),
ADD COLUMN     "mother_qualification" VARCHAR(120),
ADD COLUMN     "phone" VARCHAR(30),
ADD COLUMN     "pin_code" VARCHAR(20),
ADD COLUMN     "previous_school" VARCHAR(250),
ADD COLUMN     "religion" VARCHAR(80),
ADD COLUMN     "standard_sought" VARCHAR(50),
ADD COLUMN     "state" VARCHAR(80);
